### ISSUE TITLE
Must have either authorization code, ID token, or access token to authenticate

### ISSUE THREAD

**Issue by eseceve** [sqrrrl/passport-google-plus#8]
I see this error when I load `http://localhost:8000/auth/google` :

```
Error: Must have either authorization code, ID token, or access token to authenticate. 
at Strategy.authenticate (.../node_modules/passport-google-plus/lib/strategy.js:149:17) 
at attempt (.../node_modules/passport/lib/middleware/authenticate.js:341:16) 
at Object.authenticate [as handle] (.../node_modules/passport/lib/middleware/authenticate.js:342:7) 
at next_layer (.../node_modules/express/lib/router/route.js:103:13) 
at Route.dispatch (.../node_modules/express/lib/router/route.js:107:5) 
at c (.../node_modules/express/lib/router/index.js:195:24) 
at Function.proto.process_params (.../node_modules/express/lib/router/index.js:251:12) 
at next (.../node_modules/express/lib/router/index.js:189:19) 
at Function.proto.handle (.../node_modules/express/lib/router/index.js:234:5) 
at Layer.router (.../node_modules/express/lib/router/index.js:23:12)
```

And this is my config:

``` javascript
passport.use(new GooglePlusStrategy({
      clientId: 'my CLIENT ID',
      clientSecret: 'my CLIENT SECRET'
    }, callback);
```

``` javascript
router
  .get('/', passport.authenticate('google', {
    failureRedirect: '/signup',
    scope: [
      'profile',
      'email'
    ],
    session: false
  }))

  .get('/callback', passport.authenticate('google', {
    failureRedirect: '/signup',
    session: false
  }), auth.setTokenCookie);
```

So, where is my error?

**Comment by palakbhansali** [comment]
i was facing same problem. And the mistake could be silly, but after constant search to understand where the **token**/**authResult['code']** is in use at server passport code, i figured out that the **token parameter name** i was sending from _signInCallback_ function to server was required to be same as docs.

```
$scope.signInCallback = function (authResult) {
        //if (authResult['status']['method'] === 'PROMPT') {
        $rootScope.isBusy = true;
        if (authResult['code']) {
            var userSignIn = $resource('/api/auth/google/callback', {method: 'POST'});
            userSignIn.save({}, {code: authResult['code']}, function (data) { // see the para name, it must be code
             // incoming data object from POST
            }, function (error) {
                // Redirect to failure page
            });
        } else if (authResult['error']) {
     // Redirect to failure page
        }
        //}
    };
```

**Comment by blackkara** [comment]
I had same issue too, now fixed ! Actually i inspired by @allenp suggestion, thanks !

If you are not using bodyParser <b>OR  placing after '/auth/google/callback' route definition </b>, callback method cannot receive posted values from client, as a result <b>passport.authenticate('google')</b> will say this issue.

**Comment by kopertop** [comment]
I'm having this exact same problem, but it's not because of the code not being available, it's because of an issue with how the "param" function works on line 138 of strategy.js.

I updated it to this:

```
  var param = function(name) {
    var params = req.params || {};
    var body = req.body || {};
    var query = req.query || {};
    if (null !== params[name] && undefined !== params[name] && params.hasOwnProperty(name)) return params[name];
    if (null !== body[name] && undefined !== body[name]) return body[name];
    if (null !== query[name] && undefined !== query[name]) return query[name];
    return undefined;
  };
```

The problem was that params[name] was returning undefined, which is not == null. Adding the && undefined !== bits made this work properly.

I'll submit a pull-request for this fix.

**Comment by krajkumar6** [comment]
I get the same error and below is how I'm passing the authorization code in the $http service. Can someone  help me find what I'm doing wrong.

```
$http({
                method: 'POST',
                url:"/auth/google/accesstoken",

                params:
                   {
                   "code":response.code
                    }
                /*headers:{
                //Authorization : "Bearer " + self.accesstoken
                //access_token : "Bearer "+self.accesstoken
                code:response.code
                }*/
               }).then(function successCallback(srresponse){

                  self.userobj=srresponse.data;
                  $log.log('google passport authenticated user:',srresponse.data);
                  $cookies.putObject('usrobj',srresponse.data);
                  deferred.resolve(self.userobj);

                },function errorCallback(srresponse){
                  $log.error("http request for user login failed");
                  deferred.reject(srresponse.statusText);
              }); //$http google+
```
